export interface DayUpgrade {
  day: number;
  date?: string;
  title: string;
  category: 'Hard Skill' | 'Soft Skill' | 'Specialize';
  topic: string;
  summary: string;
  completed: boolean;
  tab: string;
  phase: number;
  keyQuestion: string;
}

export const DAILY_UPGRADES: DayUpgrade[] = [
  // ─── Phase 0: Setup ────────────────────────────────────────────────────────
  {
    day: 0,
    title: 'Project Setup',
    category: 'Hard Skill',
    topic: 'Next.js + Portfolio Foundation',
    summary: 'Setup Next.js App Router, design system, routing, migrate HTML content vào data layer.',
    completed: true,
    tab: 'Hard Skill',
    phase: 0,
    keyQuestion: 'Tại sao dùng App Router thay Pages Router? Folder structure của App Router hoạt động thế nào?',
  },

  // ─── Phase 1: Foundation (Day 1–10) ────────────────────────────────────────
  {
    day: 1,
    title: 'HTML5 Semantic Elements',
    category: 'Hard Skill',
    topic: 'HTML5 / Accessibility',
    summary: 'section, article, nav, main, aside — khi nào dùng gì. Anti-pattern: div soup vs semantic HTML.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: '<section> vs <div> khác gì? Browser và screen reader đọc khác nhau thế nào?',
  },
  {
    day: 2,
    title: 'CSS Flexbox Mastery',
    category: 'Hard Skill',
    topic: 'CSS Layout',
    summary: 'Main axis vs cross axis, flex-direction, justify-content, align-items. Biết visual model trước khi nhớ property.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Tại sao align-items hoạt động trên cross axis? Main axis thay đổi thế nào khi đổi flex-direction?',
  },
  {
    day: 3,
    title: 'CSS Grid Essentials',
    category: 'Hard Skill',
    topic: 'CSS Layout',
    summary: 'grid-template, fr unit, auto-fill/auto-fit. Khi nào Grid tốt hơn Flexbox và ngược lại.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Khi nào dùng Grid thay Flexbox? fr unit tính toán thế nào trong available space?',
  },
  {
    day: 4,
    title: 'Responsive Design & Mobile-First',
    category: 'Hard Skill',
    topic: 'CSS / UX',
    summary: 'Mobile-first approach, media queries (min-width vs max-width), clamp() cho fluid typography.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Tại sao mobile-first thay vì desktop-first? min-width vs max-width media query khác gì nhau về tư duy?',
  },
  {
    day: 5,
    title: 'JS: Scope, Closure & var/let/const',
    category: 'Hard Skill',
    topic: 'JavaScript',
    summary: 'Lexical scope, closure là gì và tại sao tồn tại. var vs let trong loop — giải thích được output khác nhau.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Tại sao var trong setTimeout loop in ra cùng giá trị nhưng let thì không? Closure giữ reference hay value?',
  },
  {
    day: 6,
    title: 'JS: Array Methods & Immutability',
    category: 'Hard Skill',
    topic: 'JavaScript',
    summary: 'map, filter, reduce — tại sao React cần immutable updates. .push() vs spread operator khác gì về tác động.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Tại sao React yêu cầu immutable state? .push() vs [...arr, item] — điều gì xảy ra trong memory?',
  },
  {
    day: 7,
    title: 'JS: Async, Event Loop & Promises',
    category: 'Hard Skill',
    topic: 'JavaScript',
    summary: 'Call stack, Web APIs, microtask vs macrotask queue. Promise chain, async/await, error handling với try/catch.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Tại sao setTimeout(fn, 0) không chạy ngay? Microtask queue chạy trước hay sau macrotask?',
  },
  {
    day: 8,
    title: 'JS: DOM & Events',
    category: 'Hard Skill',
    topic: 'JavaScript',
    summary: 'Event bubbling vs capturing, event delegation, querySelector. Tại sao React dùng synthetic events thay DOM events.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Event delegation giải quyết vấn đề gì? Tại sao e.stopPropagation() đôi khi gây bug khó tìm?',
  },
  {
    day: 9,
    title: 'HTTP & REST Fundamentals',
    category: 'Hard Skill',
    topic: 'Networking',
    summary: 'GET/POST/PUT/PATCH/DELETE — dùng khi nào. Status codes 2xx/3xx/4xx/5xx. CORS là gì và tại sao tồn tại.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Tại sao browser block cross-origin request nhưng server-to-server thì không? CORS header giải quyết thế nào?',
  },
  {
    day: 10,
    title: 'Browser: URL → Pixels Pipeline',
    category: 'Hard Skill',
    topic: 'Browser Internals',
    summary: 'DNS → TCP → HTTP → HTML parse → CSSOM → Render tree → Layout → Paint → Composite. Hiểu flow này = hiểu performance.',
    completed: false,
    tab: 'Foundation',
    phase: 1,
    keyQuestion: 'Tại sao CSS blocking render nhưng JS thì blocking cả parse? Đặt <script> ở đâu và tại sao?',
  },

  // ─── Phase 2: React Core (Day 11–18) ───────────────────────────────────────
  {
    day: 11,
    title: 'React: Component & JSX',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'JSX compile thành React.createElement(). Component = function trả về UI. Tại sao không gọi MyComponent() trực tiếp.',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'JSX biến đổi thành gì sau khi compile? Gọi MyComponent() vs <MyComponent /> khác nhau thế nào với React?',
  },
  {
    day: 12,
    title: 'React: Props & Composition',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'Props là read-only — tại sao. children pattern, composition vs inheritance. Component API design.',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'Tại sao React chọn composition thay vì inheritance? children prop giải quyết vấn đề gì mà props thường không giải được?',
  },
  {
    day: 13,
    title: 'React: useState Deep Dive',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'State batching, functional updates. Tại sao setCount(count+1) gọi 3 lần chỉ tăng 1. setState async hay sync?',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'setCount(count+1) 3 lần vs setCount(c=>c+1) 3 lần — kết quả khác nhau thế nào và tại sao?',
  },
  {
    day: 14,
    title: 'React: useEffect Deep Dive',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'Dependency array (Object.is comparison), cleanup function, AbortController pattern. Tại sao missing deps = bug.',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'Cleanup function trong useEffect chạy khi nào? Làm sao cancel API call khi component unmount?',
  },
  {
    day: 15,
    title: 'React: useRef, useMemo, useCallback',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'useRef không trigger re-render. useMemo/useCallback — khi nào thực sự cần vs premature optimization.',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'useRef vs useState — điều gì xảy ra với render khi update mỗi cái? Khi nào useMemo làm app chậm hơn?',
  },
  {
    day: 16,
    title: 'React: Forms & Validation',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'Controlled vs uncontrolled inputs. Validation timing (onChange/onBlur/onSubmit). react-hook-form + Zod integration.',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'Controlled vs uncontrolled — khi nào chọn cái nào? Tại sao validate onBlur thay vì onChange cho UX tốt hơn?',
  },
  {
    day: 17,
    title: 'React: State Management Levels',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'Local → lifting state → Context → Zustand/Jotai. Mỗi level giải quyết vấn đề gì mà level trước không giải được.',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'Context API gây re-render vấn đề gì? Khi nào Context đủ dùng và khi nào cần Zustand?',
  },
  {
    day: 18,
    title: 'React: Data Fetching Patterns',
    category: 'Hard Skill',
    topic: 'React',
    summary: 'Loading/Error/Success state machine. Race condition, stale closure. Tại sao TanStack Query / SWR tồn tại.',
    completed: false,
    tab: 'React',
    phase: 2,
    keyQuestion: 'Race condition trong data fetching xảy ra thế nào? Cache invalidation là vấn đề gì mà TanStack Query giải?',
  },

  // ─── Phase 3: TypeScript + Next.js + Tooling (Day 19–26) ───────────────────
  {
    day: 19,
    title: 'TypeScript: Basics & Type System',
    category: 'Hard Skill',
    topic: 'TypeScript',
    summary: 'interface vs type, union, intersection, generics. TypeScript là structural typing — khác nominal typing thế nào.',
    completed: false,
    tab: 'TypeScript',
    phase: 3,
    keyQuestion: 'interface vs type — khi nào dùng cái nào? Generics giải quyết vấn đề gì mà any không giải được?',
  },
  {
    day: 20,
    title: 'TypeScript cho React',
    category: 'Hard Skill',
    topic: 'TypeScript',
    summary: 'Type props, event handlers, children, hooks. React.FC có nên dùng không. Zod cho runtime validation.',
    completed: false,
    tab: 'TypeScript',
    phase: 3,
    keyQuestion: 'Tại sao React.FC bị nhiều người không recommend? Type event handler khác nhau thế nào giữa onClick và onChange?',
  },
  {
    day: 21,
    title: 'Next.js: App Router Architecture',
    category: 'Hard Skill',
    topic: 'Next.js',
    summary: 'Server Component vs Client Component — khác biệt cơ bản. use client directive, hydration, streaming.',
    completed: false,
    tab: 'Next.js',
    phase: 3,
    keyQuestion: '"use client" nghĩa là gì thực sự — file đó có chạy trên server không? Hydration là gì và tại sao cần?',
  },
  {
    day: 22,
    title: 'Next.js: Data, Layouts & Error UI',
    category: 'Hard Skill',
    topic: 'Next.js',
    summary: 'Layouts, loading.tsx, error.tsx, Server Actions, Route Handlers. Khi nào fetch ở server vs client.',
    completed: false,
    tab: 'Next.js',
    phase: 3,
    keyQuestion: 'Server Actions khác API Route thế nào? Fetch trong Server Component có đi qua browser không?',
  },
  {
    day: 23,
    title: 'Git Workflow cho Team',
    category: 'Hard Skill',
    topic: 'Git',
    summary: 'Feature branch strategy, conventional commits, PR template, conflict resolution, interactive rebase.',
    completed: false,
    tab: 'Git',
    phase: 3,
    keyQuestion: 'git rebase vs git merge — khi nào dùng cái nào? Conventional commits giúp gì cho team và automation?',
  },
  {
    day: 24,
    title: 'Figma → Code Workflow',
    category: 'Hard Skill',
    topic: 'Design → Code',
    summary: 'Đọc design tokens, spacing system, typography scale, responsive breakpoints từ Figma. Pixel-perfect vs pragmatic.',
    completed: false,
    tab: 'Hard Skill',
    phase: 3,
    keyQuestion: 'Design token là gì? Làm sao biết một element trong Figma nên dùng padding hay margin?',
  },
  {
    day: 25,
    title: 'Browser DevTools Mastery',
    category: 'Hard Skill',
    topic: 'Debugging',
    summary: 'Elements, Console, Network, Performance tabs. Đọc waterfall chart, debug network requests, profiling re-renders.',
    completed: false,
    tab: 'Hard Skill',
    phase: 3,
    keyQuestion: 'Network waterfall chart đọc thế nào? TTFB là gì và nó bị ảnh hưởng bởi yếu tố nào?',
  },
  {
    day: 26,
    title: 'Build Tools & Developer Experience',
    category: 'Hard Skill',
    topic: 'Tooling',
    summary: 'Tại sao Vite nhanh hơn Webpack (ESM vs bundling). ESLint + Prettier, husky pre-commit, env variables.',
    completed: false,
    tab: 'Hard Skill',
    phase: 3,
    keyQuestion: 'Vite dùng ESM thay vì bundle trong dev — điều đó nghĩa là gì cho HMR speed? .env vs .env.local khác gì?',
  },

  // ─── Phase 4: Soft Skills + Quality (Day 27–33) ─────────────────────────────
  {
    day: 27,
    title: 'STAR Method cho Interview',
    category: 'Soft Skill',
    topic: 'Communication',
    summary: 'Situation, Task, Action, Result. Chuẩn bị 3 câu STAR cho frontend scenarios. Anti-pattern: kể chuyện không có Result.',
    completed: false,
    tab: 'Soft Skills',
    phase: 4,
    keyQuestion: 'STAR answer của bạn cho câu: "Tell me about a time you had a bug you couldn\'t solve — what did you do?"',
  },
  {
    day: 28,
    title: 'English Technical Communication',
    category: 'Soft Skill',
    topic: 'Communication',
    summary: 'Daily standup bằng tiếng Anh, PR description, code review comments. Template + 10 phrases thông dụng.',
    completed: false,
    tab: 'Soft Skills',
    phase: 4,
    keyQuestion: 'Viết PR description bằng tiếng Anh cho một feature bạn vừa làm. Bao gồm: What, Why, How to test.',
  },
  {
    day: 29,
    title: 'Code Review Etiquette',
    category: 'Soft Skill',
    topic: 'Collaboration',
    summary: 'Give feedback không offensive, receive feedback không defensive. STAR example: lần đầu bị reject PR.',
    completed: false,
    tab: 'Soft Skills',
    phase: 4,
    keyQuestion: '"This is wrong" vs "This might cause X issue because Y, consider Z" — tại sao cách sau tốt hơn cho team?',
  },
  {
    day: 30,
    title: 'Task Estimation & Breaking Down Work',
    category: 'Soft Skill',
    topic: 'Planning',
    summary: 'T-shirt sizing, story points, breaking feature thành tasks nhỏ. Tại sao estimate sai và cách buffer hợp lý.',
    completed: false,
    tab: 'Soft Skills',
    phase: 4,
    keyQuestion: 'Senior thường estimate task nào đó 2 ngày, junior estimate 1 ngày — gap đến từ đâu?',
  },
  {
    day: 31,
    title: 'Testing: Unit & Component Tests',
    category: 'Hard Skill',
    topic: 'Testing',
    summary: 'Vitest cho unit test, React Testing Library cho component. Test behavior không test implementation.',
    completed: false,
    tab: 'Testing',
    phase: 4,
    keyQuestion: 'Tại sao Testing Library không recommend query bằng className? "Test behavior, not implementation" nghĩa là gì?',
  },
  {
    day: 32,
    title: 'Clean Code & Component Patterns',
    category: 'Hard Skill',
    topic: 'Architecture',
    summary: 'DRY, single responsibility, custom hooks để extract logic, presentational vs container pattern.',
    completed: false,
    tab: 'Hard Skill',
    phase: 4,
    keyQuestion: 'Khi nào extract custom hook thay vì để logic trong component? DRY có thể bị lạm dụng thế nào?',
  },
  {
    day: 33,
    title: 'Accessibility (a11y) Basics',
    category: 'Hard Skill',
    topic: 'Accessibility',
    summary: 'ARIA roles, keyboard navigation, color contrast ratio. Tại sao semantic HTML giải quyết 80% a11y.',
    completed: false,
    tab: 'A11y',
    phase: 4,
    keyQuestion: 'Nếu đã dùng semantic HTML đúng, khi nào mới cần thêm ARIA attributes?',
  },

  // ─── Phase 5: Interview Prep + Portfolio (Day 34–40) ───────────────────────
  {
    day: 34,
    title: 'Performance & Core Web Vitals',
    category: 'Hard Skill',
    topic: 'Performance',
    summary: 'LCP, INP, CLS — đo gì và optimize thế nào. Lighthouse audit workflow. Image optimization, lazy loading.',
    completed: false,
    tab: 'Performance',
    phase: 5,
    keyQuestion: 'CLS xảy ra do nguyên nhân phổ biến nào? Làm sao fix LCP chậm khi image là LCP element?',
  },
  {
    day: 35,
    title: 'Auth Flow Basics',
    category: 'Hard Skill',
    topic: 'Security',
    summary: 'JWT vs session-based auth concept. Protected routes trong Next.js. Không bao giờ store sensitive data trong localStorage.',
    completed: false,
    tab: 'Hard Skill',
    phase: 5,
    keyQuestion: 'Tại sao không lưu JWT trong localStorage? Cookie httpOnly giải quyết vấn đề gì?',
  },
  {
    day: 36,
    title: 'Portfolio Project: Plan & Architecture',
    category: 'Specialize',
    topic: 'Career',
    summary: 'Chọn project thực tế, thiết kế component tree, data flow, API integration plan. Mục tiêu: showcase 5 skills trong 1 project.',
    completed: false,
    tab: 'Career',
    phase: 5,
    keyQuestion: 'Project của bạn showcase gì cho recruiter? Làm sao chứng minh bạn biết work với API thực tế?',
  },
  {
    day: 37,
    title: 'Portfolio Project: Build & Polish',
    category: 'Specialize',
    topic: 'Career',
    summary: 'Implement API integration, loading/error states, responsive UI. STAR format cho project description trong CV.',
    completed: false,
    tab: 'Career',
    phase: 5,
    keyQuestion: 'README của bạn giải thích được: What, Why, How to run, và What you learned chưa?',
  },
  {
    day: 38,
    title: 'Interview Prep: Frontend Questions',
    category: 'Specialize',
    topic: 'Career',
    summary: '15 câu phổ biến + cách trả lời. Closure, Event Loop, Virtual DOM, React lifecycle, CSS specificity.',
    completed: false,
    tab: 'Career',
    phase: 5,
    keyQuestion: 'Giải thích Virtual DOM cho người không biết React — dùng analogy gì? Event loop giải thích trong 30 giây?',
  },
  {
    day: 39,
    title: 'Mock Interview Practice',
    category: 'Specialize',
    topic: 'Career',
    summary: 'Self-record 30-min mock interview, review lại. Focus: clarity of explanation, không nói "ừm" quá nhiều, answer structure.',
    completed: false,
    tab: 'Career',
    phase: 5,
    keyQuestion: 'Sau khi xem lại recording: bạn giải thích có clear không? Có trả lời đúng câu được hỏi không?',
  },
  {
    day: 40,
    title: 'SWOT Review & 90-Day Junior Plan',
    category: 'Specialize',
    topic: 'Career',
    summary: 'Update SWOT sau 40 ngày. Nếu được nhận: 90-day plan cho 3 tháng đầu junior. Measurable outcomes mỗi tuần.',
    completed: false,
    tab: 'Career',
    phase: 5,
    keyQuestion: 'So với Day 0: bạn có thể trả lời được câu hỏi nào mà trước đây không trả lời được?',
  },
];

export const CATEGORY_COLOR = {
  'Hard Skill': 'var(--accent-blue)',
  'Soft Skill': 'var(--accent-green)',
  'Specialize': 'var(--accent-claude)',
};

export const PHASE_LABELS: Record<number, string> = {
  0: 'Setup',
  1: 'Foundation',
  2: 'React Core',
  3: 'TypeScript + Next.js + Tooling',
  4: 'Soft Skills + Quality',
  5: 'Interview Prep + Portfolio',
};

export function getCompletedCount(): number {
  return DAILY_UPGRADES.filter((d) => d.completed).length;
}

export function getPhaseProgress(phase: number): { completed: number; total: number } {
  const days = DAILY_UPGRADES.filter((d) => d.phase === phase);
  return {
    completed: days.filter((d) => d.completed).length,
    total: days.length,
  };
}
